name: Publish Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.2.0 or 2.5.1)"
        required: true
        type: string

jobs:
  Prepare_new_release:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - uses: TanguyBarthelemy/r-release-action@80074b519aa491bd3aa5f14e4fd66f40a77de641
        with:
          tag: ${{ github.event.inputs.tag }}
          gh_repo: "TractorTom/date4ts"
          main-branch: "main"
          dev-branch: "develop"
